name = "Project CaS"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bf3ba2ed52b3a482630bf82557372885394519b4db8c78ffbfcbff6e1ec6803"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
