name = "Project CaS"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b61cd4080359fd54a3fbf53e6ed66deb4427cc3c69b57efdb0cf2741c067ab7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
